// <auto-generated />
using System;
using CoursesMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoursesMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231219160215_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoursesMVC.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A course about Model Views and Controllers",
                            EndDate = new DateOnly(1, 1, 1),
                            StartDate = new DateOnly(1, 1, 1),
                            Title = "MVC"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Minimum viable product",
                            EndDate = new DateOnly(1, 1, 1),
                            StartDate = new DateOnly(1, 1, 1),
                            Title = "MVP"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Using Python and SQL programs networks and databases",
                            EndDate = new DateOnly(1, 1, 1),
                            StartDate = new DateOnly(1, 1, 1),
                            Title = "Network programming"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
